/* CATALÀ */
export default {
    LANGUAGE_HEADER: "Canvi d'idioma",
    PROFILE_HEADER: "Perfil",
    CALENDAR_HEADER:"Calendari",
    MEDICATION_HEADER:"Medicació",
    BLOG_HEADER:"ICOBlog",
    CONTACT_HEADER:"Contactes",
    HOSPITAL_HEADER:"Hospitals",
    COMO_LLEGAR_HEADER: "Com arribar",
    COMO_LLEGAR_HOSP_REF: "Hospital de referència",
    COMO_LLEGAR_BUS_LINEAS: "Autobús Línies",
    COMO_LLEGAR_METRO: "Metro",
    COMO_LLEGAR_OTRO_INSTR: "En cas de dirigir-se a un altre centre seleccioneu la provincia per mostrar el llistat de centres",
    COMO_LLEGAR_SELECCION_PROV: "Seleccioneu província",
    //Medicació
    ALERT_NOT_ACCESS_NOTIFICATION:"No tens permisos per poder rebre notificacions",
    ALERT_IS_A_VIRTUAL_DEVICE:"Estàs executan l'aplicació en un dispositiu virtual",
    ALERT_ALARM_HEADER:"Alarma activa",
    ALERT_ALARM_BODY:"La alarma està programada per a tots els díes a les ",
    ALERT_CLOSE_TEXT:"Tancar",
    ALERT_OK_TEXT:"Aceptar",
    ALERT_CANCEL_TEXT:"Cancelar",
    COMPRESSED_TEXT:"Comprimits",
    DAYS_TEXT:"Dies",
    INTERVAL_TEXT:"cops al dia ",
    NOTIFICATION_HEADER:"Recordi prendre la medicació",
    DETERMINAT_TEXT:" de ",
    OBSERVATION_TEXT:"Observacions",
    DOWNLOAD_RECIPE:"Descarregar recepta",
    ALARM_TEXT:"Alarma",
    //Calendari
    WEEKDAYS:['Dl', 'Dt', 'Dc', 'Dj', 'Dv', 'Ds', 'Dg'],
    MONTHS:[
        'Gener',
        'Febrer',
        'Març',
        'Abril',
        'Maig',
        'Juny',
        'Juliol',
        'Agost',
        'Setembre',
        'Octubre',
        'Novembre',
        'Desembre',
    ],
    PREVIOUS:"Anterior",
    NEXT:"Següent",
    //Perfil
    AGE:"Anys",
    MALE:"Home",
    FEMALE:"Dona",
    EDIT_PROFILE:"Editar perfil",
    GENERATE_QR:"Generar QR",
    //ICO BLOG
    ICO_BLOG_HACE_DIAS: "fa %{dias} dies"
};