/* ENGLISH */
export default {
    LANGUAGE_HEADER: "Change Language",
    PROFILE_HEADER: "Profile",
    CALENDAR_HEADER: "Calendar",
    MEDICATION_HEADER: "Medication",
    BLOG_HEADER: "ICOBlog",
    CONTACT_HEADER: "Contacts",
    HOSPITAL_HEADER: "Hospitals",
    COMO_LLEGAR_HEADER: "How to get",
    COMO_LLEGAR_HOSP_REF: "Reference hospital",
    COMO_LLEGAR_BUS_LINEAS: "Bus Lines",
    COMO_LLEGAR_METRO: "Subway",
    COMO_LLEGAR_OTRO_INSTR: "In case of going to another center select the province to show the list of centers",
    COMO_LLEGAR_SELECCION_PROV: "Select province",
    //Medication
    ALERT_NOT_ACCESS_NOTIFICATION: "You do not have permissions to receive notifications",
    ALERT_IS_A_VIRTUAL_DEVICE: "You are running the application on a virtual device",
    ALERT_ALARM_HEADER: "Active alarm",
    ALERT_ALARM_BODY: "The alarm is scheduled for every day at ",
    ALERT_CLOSE_TEXT: "Close",
    ALERT_OK_TEXT: "Accept",
    ALERT_CANCEL_TEXT: "Cancel",
    COMPRESSED_TEXT: "Compressed",
    DAYS_TEXT: "Days",
    INTERVAL_TEXT: "for day ",
    NOTIFICATION_HEADER: "Remember to take the medication",
    DETERMINAT_TEXT: " of ",
    OBSERVATION_TEXT: "Observation ",
    DOWNLOAD_RECIPE: "Download recipe",
    ALARM_TEXT: "Alarm",
    //Calendar
    WEEKDAYS: ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun'],
    MONTHS: [
        'January',
        'Febraury',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ],
    PREVIOUS: "Previous",
    NEXT: "Next",
    //Profile
    AGE:"Years",
    MALE:"Male",
    FEMALE:"Female",
    EDIT_PROFILE:"Edit profile",
    GENERATE_QR:"Generate QR",
    //ICO BLOG
    ICO_BLOG_HACE_DIAS: "%{dias} days ago",
    //Date
    HOSPITAL:"Hospital",
    BUILDING:"Building",
    BOX:"Box",
    DAY:"Day",
    SCHEDULE:"Schedule",
    INDICATIONS:"Indications"

};