/* ESPAÑOL */
export default {
    LANGUAGE_HEADER: "Cambio de Idioma",
    PROFILE_HEADER: "Perfil",
    CALENDAR_HEADER: "Calendario",
    MEDICATION_HEADER: "Medicación",
    BLOG_HEADER: "ICOBlog",
    CONTACT_HEADER: "Contactos",
    HOSPITAL_HEADER: "Hospitales",
    COMO_LLEGAR_HEADER: "Cómo llegar",
    COMO_LLEGAR_HOSP_REF: "Hospital de referencia",
    COMO_LLEGAR_BUS_LINEAS: "Autobús Líneas",
    COMO_LLEGAR_METRO: "Metro",
    COMO_LLEGAR_OTRO_INSTR: "En caso de dirigirse a otro centro seleccione la província para mostrar el listado de centros",
    COMO_LLEGAR_SELECCION_PROV: "Seleccione província",
    //Medicación
    ALERT_NOT_ACCESS_NOTIFICATION: "No tienes permisos para poder recibir notificaciones",
    ALERT_IS_A_VIRTUAL_DEVICE: "Estás ejecutando la aplicación en un dispositivo virtual",
    ALERT_ALARM_HEADER: "Alarma activa",
    ALERT_ALARM_BODY: "La alarma está programada para todos los días a las",
    ALERT_CLOSE_TEXT: "Cerrar",
    ALERT_OK_TEXT: "Aceptar",
    ALERT_CANCEL_TEXT: "Cancelar",
    COMPRESSED_TEXT: "Comprimidos",
    DAYS_TEXT: "Dias",
    INTERVAL_TEXT: "veces al día ",
    NOTIFICATION_HEADER: "Recuerda tomar la medicación",
    DETERMINAT_TEXT: " de ",
    OBSERVATION_TEXT: "Observaciones",
    DOWNLOAD_RECIPE: "Descargar receta",
    ALARM_TEXT: "Alarma",
    //Calendario
    WEEKDAYS: ['Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa', 'Do'],
    MONTHS: [
        'Enero',
        'Febrero',
        'Marzo',
        'Abril',
        'Mayo',
        'Junio',
        'Julio',
        'Agosto',
        'Septiembre',
        'Octubre',
        'Noviembre',
        'Diciembre',
    ],
    PREVIOUS: "Anterior",
    NEXT: "Siguiente",
    //Perfil
    AGE:"Años",
    MALE:"Hombre",
    FEMALE:"Mujer",
    EDIT_PROFILE:"Editar perfil",
    GENERATE_QR:"Generar QR"

};